# ./ansible/requirements.yml
---
collections:
  - name: cloud.terraform
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=1.5.4"

roles:
  - name: monolithprojects.github_actions_runner
    version: 1.18.7
